# Overlay file for Aviva Solutions SXA specific Docker image names
version: '2.4'

services:
  mssql:
    image: "avivasolutionsnl.azurecr.io/sitecore-mssql-sxa:${TAG}"

  sitecore:
    image: "avivasolutionsnl.azurecr.io/sitecore-sitecore-sxa:${TAG}"

  solr:
    image: "avivasolutionsnl.azurecr.io/sitecore-solr-sxa:${TAG}"

  xconnect:
    image: "avivasolutionsnl.azurecr.io/sitecore-xconnect:${TAG}"
