version: '2.4'

services:
  sitecore:
    image: "${IMAGE_PREFIX}sitecore:${TAG}"
    volumes:
      - .\sitecore\sxa:C:\sxa
      - ..\files:C:\files-mount
    environment:
      PSE_PACKAGE: ${PSE_PACKAGE}
      SXA_PACKAGE: ${SXA_PACKAGE}
      SCXA_PACKAGE: ${SCXA_PACKAGE}

  mssql:
    image: "${IMAGE_PREFIX}mssql:${TAG}"

  solr:
    image: "${IMAGE_PREFIX}solr-sxa:${TAG}"