version: '2.4'

services:
  sitecore:
    volumes:
      - .\sitecore\sxa:C:\sxa
      - ..\files:C:\files-mount
    environment:
      PSE_PACKAGE: ${PSE_PACKAGE}
      SXA_PACKAGE: ${SXA_PACKAGE}
      DataExchangeFrameworkPackage: ${DataExchangeFrameworkPackage}
      SqlProviderPackage: ${SqlProviderPackage}
      SitecoreProviderPackage : ${SitecoreProviderPackage}
      XConnectProviderPackage: ${XConnectProviderPackage}
      DynamicsProviderPackage: ${DynamicsProviderPackage}
      ConnectForDynamicsPackage: ${ConnectForDynamicsPackage}

